/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Phone_Application;

/**
 *
 * @author Akabir Abbas
 */

import java.awt.Color;
import java.awt.event.FocusListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;


import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

class NumericFilter extends DocumentFilter {
    @Override
    public void insertString(FilterBypass fb, int offset, String text, AttributeSet attr)
            throws BadLocationException {
        // Allow only digits to be inserted
        if (text.matches("\\d+")) {
            super.insertString(fb, offset, text, attr);
        }
    }

    @Override
    public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
            throws BadLocationException {
        // Allow only digits to be replaced
        if (text.matches("\\d+")) {
            super.replace(fb, offset, length, text, attrs);
        }
    }
}


public class Add_Contacts extends javax.swing.JFrame {
    private static Map<String, Contact> contacts = new HashMap<>();

    /**
     * Creates new form Add_Contacts
     */
    public Add_Contacts() {
        initComponents();
        // Set default text and add focus listener for each text field
        setDefaultText(jTextField1, "Enter First Name");
        setDefaultText(jTextField2, "Enter Last Name");
        setDefaultText(jTextField3, "Enter Phone Number");
        setDefaultText(jTextField4, "Enter Work Phone Number");
        setDefaultText(jTextField5, "Enter Company");
        setStyles();  // Call the method to set styles
    }
    
    private void setDefaultText(JTextField textField, String defaultText) {
        textField.setText(defaultText);

        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(defaultText)) {
                    textField.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(defaultText);
                }
            }
        });
    }
    
    private static void addContact(String firstName, String lastName, String phoneNumber, String workPhoneNumber, String company) {
        Contact contact = new Contact(firstName, lastName, phoneNumber, workPhoneNumber, company);
        contacts.put(firstName + " " + lastName, contact);
        // System.out.println("Contact added successfully!");
    }
    
    
    private void setStyles() {
    // Set background color or image
    getContentPane().setBackground(new java.awt.Color(240, 240, 240)); // You can change the color as per your choice

    // Set button styles
    javax.swing.JButton[] buttons = {jButton1, jButton2};
  
    
    for (javax.swing.JButton button : buttons) {
        button.setBackground(new java.awt.Color(255, 255, 255)); // Button background color
        button.setFont(new java.awt.Font("Tahoma", 1, 14)); // Button font
        
         // Set font color using RGB values
        int red = 134;   // Replace with your desired RGB values
        int green = 134;
        int blue = 141;

        
        Color textColor = new Color(red, green, blue);

        
        button.setForeground(textColor);
        

        // Set opacity
        button.setOpaque(false); // Make the button transparent
        button.setContentAreaFilled(false); // Don't paint the inside of the button
        button.setBorderPainted(false); // Don't paint the border of the button
        
         // Set font color of jLabel1 to white

    }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 44));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 44));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, 44));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, 44));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, 44));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 30, 20));

        jButton2.setText("Back To Contacts");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 30, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Phone_Application/AddContacts-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Contacts contacts = new Contacts();
        contacts.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String firstName = jTextField1.getText();
        String lastName = jTextField2.getText();
        String phoneNumber = jTextField3.getText();
        String workPhoneNumber = jTextField4.getText();
        String company = jTextField5.getText();

        addContact(firstName, lastName, phoneNumber, workPhoneNumber, company);
        
            View_Contacts viewContacts = new View_Contacts(contacts);
            viewContacts.setVisible(true);

    // Close the current window
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Contacts().setVisible(true);
            }
        });
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Add_Contacts addContacts = new Add_Contacts();
            addContacts.setVisible(true);

            // Apply the NumericFilter to jTextField3
            ((AbstractDocument) addContacts.jTextField3.getDocument()).setDocumentFilter(new NumericFilter());
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables


    static class Contact {
        private String firstName;
        private String lastName;
        private String phoneNumber;
        private String workPhoneNumber;
        private String company;

        public Contact(String firstName, String lastName, String phoneNumber, String workPhoneNumber, String company) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.phoneNumber = phoneNumber;
            this.workPhoneNumber = workPhoneNumber;
            this.company = company;
        }

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }

        public String getPhoneNumber() {
            return phoneNumber;
        }

        public void setPhoneNumber(String phoneNumber) {
            this.phoneNumber = phoneNumber;
        }

        public String getWorkPhoneNumber() {
            return workPhoneNumber;
        }

        public void setWorkPhoneNumber(String workPhoneNumber) {
            this.workPhoneNumber = workPhoneNumber;
        }

        public String getCompany() {
            return company;
        }

        public void setCompany(String company) {
            this.company = company;
        }
        
        
        
        
        public String toString() {
        // Provide a meaningful representation of the Contact object
        return  getPhoneNumber()
                + "\nWork Phone Number: " + getWorkPhoneNumber();
    }
        
        

}
    
}
