/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Phone_Application;

import java.awt.Color;
import java.util.List;
import java.util.Set;
import javax.swing.SwingConstants;

/**
 *
 * @author Akabir Abbas
 */
public class Call_History extends javax.swing.JFrame {

    /**
     * Creates new form Call_History
     */
    public Call_History() {
        initComponents();
        setStyles();  // Call the method to set styles
    }
    
    void updateCallHistory(Set<String> callHistory) {
    StringBuilder historyText = new StringBuilder();

    for (String phoneNumber : callHistory) {
        Call_Screen.CallHistoryEntry entry = Call_Screen.callHistory.get(phoneNumber);
        if (entry != null) {
            // Append dialed number and call time to the history text
            historyText.append("Number: ").append(phoneNumber)
                    .append(", Call Time: ").append(entry.getFormattedCallTime()).append("\n");
        }
    }

    jTextArea1.setText(historyText.toString());
}
     
     
     private void setStyles() {
    // Set background color or image
    getContentPane().setBackground(new java.awt.Color(240, 240, 240)); // You can change the color as per your choice

    // Set button styles
    javax.swing.JButton[] buttons = {jButton1, jButton2};
  
    
    for (javax.swing.JButton button : buttons) {
        button.setBackground(new java.awt.Color(255, 255, 255)); // Button background color
        button.setFont(new java.awt.Font("Tahoma", 1, 14)); // Button font
        
         // Set font color using RGB values
        int red = 134;   // Replace with your desired RGB values
        int green = 134;
        int blue = 141;

        
        Color textColor = new Color(red, green, blue);

        
        button.setForeground(textColor);
        

        // Set opacity
        button.setOpaque(false); // Make the button transparent
        button.setContentAreaFilled(false); // Don't paint the inside of the button
        button.setBorderPainted(false); // Don't paint the border of the button
        
         // Set font color of jLabel1 to white
    jLabel1.setForeground(Color.WHITE);
    }

    // Set label styles
    jLabel1.setBackground(new java.awt.Color(255, 255, 255)); // Label background color
    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // Label font
    jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Call History");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 88));

        jButton1.setText("Back To Phone");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 43, -1));

        jButton2.setText("Clear History");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 373, 41, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, 170, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Phone_Application/call_history.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Phone phone = new Phone();

        phone.setVisible(true);



        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // Clear History button clicked
        Call_Screen.clearCallHistory();
        jTextArea1.setText(""); // Clear the displayed history
     

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Call_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Call_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Call_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Call_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Call_History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
