/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Phone_Application;


import java.awt.Color;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextArea;


/**
 *
 * @author Akabir Abbas
 */
public class View_Contacts extends javax.swing.JFrame {

    /**
     * Creates new form View_Contacts
     */
    
   private static Map<String, Add_Contacts.Contact> contacts;

    public View_Contacts(Map<String, Add_Contacts.Contact> contacts) {
        initComponents();
        this.contacts = contacts;
        displayContacts(contacts);
        jButton5.setText("Call");
    jButton5.setEnabled(false); // Initially set to disabled
    setStyles();
    
//    setButtonTransparency(jButton1);
//        setButtonTransparency(jButton2);
//        setButtonTransparency(jButton3);
//        setButtonTransparency(jButton4);
    
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
       
    });
    }
    
    private void setStyles() {
    // Set background color or image
    getContentPane().setBackground(new java.awt.Color(240, 240, 240)); // You can change the color as per your choice

    // Set button styles
    javax.swing.JButton[] buttons = {jButton1, jButton2, jButton3, jButton4, jButton5};

    for (javax.swing.JButton button : buttons) {
        button.setBackground(new java.awt.Color(255, 255, 255)); // Button background color
        button.setFont(new java.awt.Font("Tahoma", 1, 14)); // Button font
        
        button.setOpaque(false); // Make the button transparent
        button.setContentAreaFilled(false); // Don't paint the inside of the button
        button.setBorderPainted(false); // Don't paint the border of the button
    }
    }


    private View_Contacts() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    


    

    
    
    // Method to search for a contact by name
private void searchContact(String name) {
        // Retrieve the contacts map
        Map<String, Add_Contacts.Contact> contacts = getContacts();

        // Check if the contact is present in the map
        if (contacts.containsKey(name)) {
            // Display the contact information
//            jTextArea1.setText("Contact found:\nName: " + name + "\nPhone Number: " + contacts.get(name));
            jTextArea1.setText("Contact found:\nName: " + name + "\nPhone Number: " + contacts.get(name));
            jButton5.setEnabled(true);
        
        } else {
            // Display a message if the contact is not found
            jTextArea1.setText("Contact not found.");
            jButton5.setEnabled(false);
        }
    }
    
void displayContacts(Map<String, Add_Contacts.Contact> contacts) {
        StringBuilder contactInfo = new StringBuilder();

        for (Map.Entry<String, Add_Contacts.Contact> entry : contacts.entrySet()) {
            Add_Contacts.Contact contact = entry.getValue();
            contactInfo.append("Name: ").append(contact.getFirstName()).append(" ").append(contact.getLastName())
                    .append("\nPhone Number: ").append(contact.getPhoneNumber())
                    .append("\nWork Phone Number: ").append(contact.getWorkPhoneNumber()).append("\n")
                    .append("-------------------------------------").append("\n");
            
             //System.out.println();
        }
        jTextArea1.setText(contactInfo.toString());
    }

 public Map<String, Add_Contacts.Contact> getContacts() {
        return contacts;
    }

//private Map<String, Contact> getContacts() {
//    return contacts;
//}




  
  // Method to search for a contact by name

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Return to Contacts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 10));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 20, 10));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 30));

        jButton3.setText("Return to Add Contacts");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 40, 10));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 270));

        jButton4.setText("Delete Contect");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 40, 20));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Phone_Application/call_button.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Phone_Application/viewContact-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Contacts contact = new Contacts();
        
        contact.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Add_Contacts addContacts = new Add_Contacts();
        
        addContacts.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String searchName = jTextField1.getText().trim();
        
        if (!searchName.isEmpty()) {
        searchContact(searchName);
    } else {
        // Display a message if the searchName is empty
        jTextArea1.setText("Please enter a name to search for.");
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //addContact(firstName, lastName, phoneNumber, workPhoneNumber, company);
        //Add_Contacts.Contact contact;
        //contact = new Add_Contacts.Contact(getFirstName, getlastName, getphoneNumber, getworkPhoneNumber, getcompany);
        Delete_Contacts deleteContacts = new Delete_Contacts(contacts, this);
        deleteContacts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String dialedNumber = jTextField1.getText();
        Call_Screen callScreen = new Call_Screen();
        callScreen.setDialedNumber(dialedNumber);
        
        // Make the Call_Screen frame visible
        callScreen.setVisible(true);
    
        // Close the current Phone frame if needed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Contacts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables




}
